import TopBar from "@/components/common/top-bar";
import "@fontsource/pretendard/400.css";
import "@fontsource/pretendard/500.css";
import "@fontsource/pretendard/600.css";
import "@fontsource/pretendard/700.css";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className={`h-full antialiased`}>
      <body className="min-h-full flex flex-col font-pretendard antialiased ">
        <TopBar />
        <div className="flex flex-col max-w-7xl w-full mx-auto py-10">
          {children}
        </div>
      </body>
    </html>
  );
}
